import type { JSONSchema7 } from "json-schema";
import type { FieldMapping } from "./field-mappings.js";
import { ALL_FIELD_MAPPINGS } from "./field-mappings.js";

/**
 * Formats json-schema-faker can actually generate a value for.
 *
 * Deferring to a declared `format` only helps when something downstream honors
 * it. A spec is free to declare a vocabulary format nothing implements
 * (`format: iso-country-code` in the wild), and for those json-schema-faker
 * falls back to an arbitrary string — strictly worse than the name-based
 * mapping this module would otherwise supply. So the skip below applies to
 * known formats only.
 *
 * The source of truth is json-schema-faker's own built-in format registry, and
 * `generateWithJsf` starts from that registry alone (`formats: {}`), so nothing
 * can add to it at runtime. `uri-template` and `regex` are standard Draft 7
 * formats but are NOT in it — they generated the plain random string this set
 * exists to avoid — so they are deliberately absent. `field-name-matcher.test.ts`
 * pins every member against real generation, which is what keeps this list from
 * drifting on a json-schema-faker upgrade.
 */
export const GENERATABLE_FORMATS = new Set([
  "date-time",
  "date",
  "time",
  "duration",
  "email",
  "idn-email",
  "hostname",
  "idn-hostname",
  "ipv4",
  "ipv6",
  "uri",
  "uri-reference",
  "iri",
  "iri-reference",
  "json-pointer",
  "relative-json-pointer",
  "uuid",
  // Generated by Schmock itself (jsf-config.ts SCHMOCK_FORMATS), not JSF.
  "byte",
]);

/** True when `format` names something the generator can satisfy. */
function isGeneratableFormat(format: unknown): boolean {
  return typeof format === "string" && GENERATABLE_FORMATS.has(format);
}

function isAsciiUpper(code: number): boolean {
  return code >= 65 && code <= 90;
}

function isAsciiLower(code: number): boolean {
  return code >= 97 && code <= 122;
}

function isAsciiDigit(code: number): boolean {
  return code >= 48 && code <= 57;
}

/**
 * Split one `_`/`-`-free segment on camelCase boundaries in a single pass.
 *
 * A boundary falls before an uppercase letter that follows a lowercase letter
 * or a digit ("userName" → user|Name, "v2Name" → v2|Name), and before the last
 * uppercase letter of a run that is followed by a lowercase letter
 * ("HTMLParser" → HTML|Parser). Only ASCII letters take part, exactly like the
 * `[A-Z]`/`[a-z]` classes of the regex pair this replaced — that pair
 * backtracked across a long uppercase run from every start position, which
 * made a hostile 100k-character property name cost seconds per request.
 */
function splitCamelSegment(segment: string, tokens: string[]): void {
  let start = 0;
  for (let index = 1; index < segment.length; index++) {
    const code = segment.charCodeAt(index);
    if (!isAsciiUpper(code)) continue;
    const previous = segment.charCodeAt(index - 1);
    const startsWord =
      isAsciiLower(previous) ||
      isAsciiDigit(previous) ||
      (isAsciiUpper(previous) &&
        index + 1 < segment.length &&
        isAsciiLower(segment.charCodeAt(index + 1)));
    if (startsWord) {
      tokens.push(segment.slice(start, index).toLowerCase());
      start = index;
    }
  }
  tokens.push(segment.slice(start).toLowerCase());
}

/**
 * Split a field name (camelCase, snake_case, kebab-case) into lowercase tokens.
 * "userFirstName" → ["user", "first", "name"]
 * "created_at"    → ["created", "at"]
 * "HTMLParser"    → ["html", "parser"]
 * "is_active"     → ["is", "active"]
 *
 * Runs in time linear in the name's length.
 */
export function tokenizeFieldName(name: string): string[] {
  const tokens: string[] = [];
  for (const segment of name.split(/[_-]/)) {
    if (segment) splitCamelSegment(segment, tokens);
  }
  return tokens;
}

/** A keyword with its tokenization computed once. */
interface TokenizedKeyword {
  tokens: string[];
  joined: string;
}

function tokenizeKeyword(keyword: string): TokenizedKeyword {
  const tokens = tokenizeFieldName(keyword);
  return { tokens, joined: tokens.join("") };
}

/**
 * Keyword tokenization is pure and the mapping table is immutable, so the
 * result is cached per mapping object. Without this, every `findBestMapping`
 * call re-tokenized all 379 keywords of the 152 built-in mappings — measured
 * at ~65µs per call, which made schema enhancement (not json-schema-faker)
 * the dominant cost of generating from a large schema.
 */
const tokenizedKeywordCache = new WeakMap<FieldMapping, TokenizedKeyword[]>();

function tokenizedKeywordsOf(mapping: FieldMapping): TokenizedKeyword[] {
  let tokenized = tokenizedKeywordCache.get(mapping);
  if (!tokenized) {
    tokenized = mapping.keywords.map(tokenizeKeyword);
    tokenizedKeywordCache.set(mapping, tokenized);
  }
  return tokenized;
}

/**
 * Trailing tokens that qualify a noun rather than name it: `phoneType` is a
 * kind of phone, not a phone number, and `emailStatus` is not an address.
 * When a field ends in one of these and a keyword does not end with it, only
 * the exact and ends-with tiers may match — the partial tiers would hand the
 * qualified field its base noun's value.
 */
const QUALIFIER_SUFFIXES = new Set([
  "type",
  "status",
  "format",
  "code",
  "kind",
]);

/**
 * An in-token substring shorter than this only counts when it lines up with
 * token edges. Short keywords (`lat`, `lon`, `long`, `name`, `age`) occur
 * inside unrelated words — latency, population, namespace — so a bare
 * `includes` turned a latency into a negative latitude.
 */
const MIN_UNALIGNED_SUBSTRING_LENGTH = 5;

/** A field name tokenized once, with the offsets of its token edges. */
interface TokenizedField {
  tokens: string[];
  joined: string;
  starts: Set<number>;
  ends: Set<number>;
  qualifier: string | undefined;
}

function tokenizeField(tokens: string[]): TokenizedField {
  const starts = new Set<number>();
  const ends = new Set<number>();
  let offset = 0;
  for (const token of tokens) {
    starts.add(offset);
    offset += token.length;
    ends.add(offset);
  }
  const last = tokens[tokens.length - 1];
  return {
    tokens,
    joined: tokens.join(""),
    starts,
    ends,
    qualifier:
      tokens.length > 1 && last !== undefined && QUALIFIER_SUFFIXES.has(last)
        ? last
        : undefined,
  };
}

/**
 * True when `joined[start, end)` covers whole tokens, allowing the last one to
 * carry a plural `s`/`es` (`urls` still contains the keyword `url`).
 */
function isTokenAligned(
  field: TokenizedField,
  start: number,
  end: number,
): boolean {
  if (!field.starts.has(start)) return false;
  if (field.ends.has(end)) return true;
  const rest = field.joined.slice(end, end + 2);
  return (
    (field.ends.has(end + 1) && rest.startsWith("s")) ||
    (field.ends.has(end + 2) && rest === "es")
  );
}

function hasSubstringMatch(field: TokenizedField, keyword: string): boolean {
  if (keyword.length < 3) return false;
  let index = field.joined.indexOf(keyword);
  while (index !== -1) {
    if (
      keyword.length >= MIN_UNALIGNED_SUBSTRING_LENGTH ||
      isTokenAligned(field, index, index + keyword.length)
    ) {
      return true;
    }
    index = field.joined.indexOf(keyword, index + 1);
  }
  return false;
}

/**
 * Score how well a set of pre-tokenized keywords matches a tokenized field.
 * Scoring rules are documented on {@link scoreMatch}.
 */
function scoreTokenizedMatch(
  field: TokenizedField,
  keywords: TokenizedKeyword[],
): number {
  const { tokens: fieldTokens, joined: fieldJoined } = field;
  let bestScore = 0;

  // Try each keyword variant, keep the highest score
  for (const { tokens: kwTokens, joined: kwJoined } of keywords) {
    // Exact match: joined tokens are identical
    if (fieldJoined === kwJoined) return 1.0;

    // Field ends with keyword tokens
    if (kwTokens.length > 0 && kwTokens.length <= fieldTokens.length) {
      const tail = fieldTokens.slice(-kwTokens.length);
      if (tail.every((t, i) => t === kwTokens[i])) {
        bestScore = Math.max(bestScore, 0.8);
      }
    }

    // A qualified field ("phoneType") admits no partial match on its noun.
    if (
      field.qualifier !== undefined &&
      kwTokens[kwTokens.length - 1] !== field.qualifier
    ) {
      continue;
    }

    // All keyword tokens present in field tokens with high coverage
    if (
      kwTokens.length > 0 &&
      kwTokens.every((kt) => fieldTokens.includes(kt))
    ) {
      const coverage = kwTokens.length / fieldTokens.length;
      const score = coverage > 0.5 ? 0.9 : 0.65;
      bestScore = Math.max(bestScore, score);
    }

    // Substring match: keyword joined appears in field joined
    if (hasSubstringMatch(field, kwJoined)) {
      bestScore = Math.max(bestScore, 0.7);
    }
  }

  return bestScore;
}

/**
 * Score how well a set of keyword tokens matches field name tokens.
 * Returns 0-1:
 *   1.0 — exact full match (joined tokens equal joined keywords)
 *   0.9 — all keyword tokens found in field tokens with high coverage (>50%)
 *   0.8 — field ends with keyword tokens
 *   0.7 — substring match: the keyword lines up with token edges ("urls"
 *         counts for "url"), or is at least 5 characters long ("myemailfield")
 *   0.65 — all keyword tokens found but low coverage (<=50%)
 *
 * A field ending in a qualifier (type, status, format, code, kind) that the
 * keyword does not end with only scores on the 1.0 and 0.8 tiers.
 */
export function scoreMatch(fieldTokens: string[], keywords: string[]): number {
  return scoreTokenizedMatch(
    tokenizeField(fieldTokens),
    keywords.map(tokenizeKeyword),
  );
}

/**
 * The single rule every heuristic in this package obeys: a schema that states
 * its own value source is never re-routed by the field name.
 *
 * `default` (which the OpenAPI normalizer also derives from `example`),
 * `const`, `enum` and `pattern` fix or constrain the value itself; `faker`
 * and `$ref` delegate it explicitly. `format` is handled by the caller, since
 * `format: "uuid"` agrees with a name mapping and an unknown format defers to
 * it.
 */
export function declaresExplicitValue(schema: JSONSchema7): boolean {
  return (
    schema.default !== undefined ||
    schema.const !== undefined ||
    schema.enum !== undefined ||
    schema.pattern !== undefined ||
    schema.$ref !== undefined ||
    ("faker" in schema && Boolean(schema.faker))
  );
}

type MappableType =
  | { mappable: true; type: string | undefined }
  | { mappable: false };

/**
 * The one non-null type a schema generates, for type gating.
 *
 * `type: [T, "null"]` (OpenAPI 3.1 / JSON Schema nullability) gates exactly
 * like `type: T`; a genuine multi-type union has no single type a name-based
 * mapping could honour, so it is reported as unmappable.
 */
function mappableType(schema: JSONSchema7): MappableType {
  if (!Array.isArray(schema.type)) {
    return { mappable: true, type: schema.type };
  }
  const nonNull = schema.type.filter((type) => type !== "null");
  if (nonNull.length === 1) return { mappable: true, type: nonNull[0] };
  return { mappable: false };
}

interface MatchResult {
  mapping: FieldMapping;
  score: number;
}

/**
 * Find the best field mapping for a given field name and schema.
 * Returns the highest-scoring match above its threshold, or undefined.
 */
export function findBestMapping(
  fieldName: string,
  schema: JSONSchema7,
  mappings: FieldMapping[] = ALL_FIELD_MAPPINGS,
): MatchResult | undefined {
  // Explicit value keywords beat every name heuristic, the uuid priority below
  // included — see `declaresExplicitValue`.
  if (declaresExplicitValue(schema)) return undefined;

  const typeInfo = mappableType(schema);
  if (!typeInfo.mappable) return undefined;
  const schemaType = typeInfo.type;

  // Priority: format:uuid always maps to string.uuid
  if (schemaType === "string" && schema.format === "uuid") {
    return {
      mapping: {
        keywords: ["uuid"],
        fakerMethod: "string.uuid",
        schemaType: "string",
        minScore: 0.5,
      },
      score: 1.0,
    };
  }

  // Skip if schema declares a generatable format.
  // `format` is a declared contract and json-schema-faker gives the `faker`
  // extension precedence over it, so a name-based mapping would silently
  // override the declared format (an email address in a `date-time` field).
  // Preserving `format` is not sufficient — mappings such as "name" set no
  // format at all — so the mapping is skipped entirely and json-schema-faker's
  // own format generator produces the value. `format: "uuid"` is handled by the
  // priority return above, the one case where name and format agree. An
  // unrecognized format (see GENERATABLE_FORMATS) is NOT deferred to: nothing
  // downstream can satisfy it, so skipping would trade a good name-based value
  // for an arbitrary string.
  // Also skip string mappings when minLength/maxLength is set — name-based
  // mappings (e.g. lorem.word for "label") don't honor JSON Schema length
  // constraints, so they'd produce out-of-range strings ~20% of the time.
  // Mirrors the numeric constraint skip just below.
  if (
    isGeneratableFormat(schema.format) ||
    (schemaType === "string" &&
      (schema.minLength !== undefined || schema.maxLength !== undefined))
  ) {
    return undefined;
  }

  // Skip numeric faker mapping when schema already constrains the value.
  // `multipleOf` counts: faker's numeric generators don't honor it, so a
  // mapped "age" would come back as 44 for `multipleOf: 10`.
  const hasNumericConstraints =
    schema.minimum !== undefined ||
    schema.maximum !== undefined ||
    schema.exclusiveMinimum !== undefined ||
    schema.exclusiveMaximum !== undefined ||
    schema.multipleOf !== undefined;

  // A constrained number/integer schema can't be satisfied by any name-based
  // mapping, whatever the mapping declares — several mappings (e.g. "price")
  // carry no schemaType at all and would otherwise slip through.
  const isNumericSchema = schemaType === "number" || schemaType === "integer";

  const tokens = tokenizeFieldName(fieldName);
  const field = tokenizeField(tokens);

  let best: MatchResult | undefined;

  for (const mapping of mappings) {
    // Skip numeric faker mappings when schema has explicit constraints
    if (
      hasNumericConstraints &&
      (isNumericSchema ||
        mapping.schemaType === "number" ||
        mapping.schemaType === "integer")
    ) {
      continue;
    }

    // Skip faker mappings for object/array schemas — they generate primitive values
    if (schemaType === "object" || schemaType === "array") {
      continue;
    }

    // Check schema type constraint
    if (mapping.schemaType && schemaType && mapping.schemaType !== schemaType) {
      const isNumeric =
        (mapping.schemaType === "number" && schemaType === "integer") ||
        (mapping.schemaType === "integer" && schemaType === "number");
      if (!isNumeric) continue;
    }

    const score = scoreTokenizedMatch(field, tokenizedKeywordsOf(mapping));
    if (score >= mapping.minScore && (!best || score > best.score)) {
      best = { mapping, score };
    }
  }

  // ID suffix detection: fields ending in Id/_id with string type → UUID
  // Only if no better match was found or the existing match is weak
  if (schemaType === "string") {
    const lastToken = tokens[tokens.length - 1];
    if (lastToken === "id" && tokens.length > 1) {
      const idScore = 0.8;
      if (!best || best.score < idScore) {
        best = {
          mapping: {
            keywords: ["id"],
            fakerMethod: "string.uuid",
            schemaType: "string",
            minScore: 0.5,
          },
          score: idScore,
        };
      }
    }
  }

  return best;
}
