on:
  push:
    branches: [develop]

name: Develop Branch

concurrency:
  group: develop-${{ github.sha }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  develop-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Clean workspace
        run: |
          rm -rf ./* || true
          rm -rf ./.??* || true
          
      - uses: actions/checkout@v4
        with:
          clean: true
          fetch-depth: 1
      
      - uses: ./.github/actions/setup-bun
      - uses: ./.github/actions/build
      - uses: ./.github/actions/prevent-uncommit-changes
      
      - name: Run linting
        run: bun run lint
      
      - name: Run type checking
        run: bun run typecheck
      
      - name: Run unit tests
        run: bun run test:unit
      
      - name: Run BDD tests
        run: bun run test:bdd
      
      - name: Run E2E tests
        run: bun run test:e2e